### PR TITLE
Wait on gRPC readiness (#10)

### LINKED ISSUE #10: Wait on gRPC readiness
**Is your feature request related to a problem? Please describe.**
At the moment, we're restricted to a fairly basic HTTP based wait. If would be good if we could wait on a gRPC service to become available.

### PR DESCRIPTION
**Pull request by ahdekkers**
# Description

Added dependencies: [context](https://pkg.go.dev/context) and [grpc](https://pkg.go.dev/google.golang.org/grpc). 

Fixes #10

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Running existing tests
- [x] Created new tests

# Checklist:

- [ ] My code has been linted (`make lint`)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes (`make test lint build acceptance-test`)
- [x] I have rebased my branch to include the latest changes from `master`

### CODE REVIEW

**Comment by dnnrly** [comment]
First of all, a massive thank you for this contribution! It really makes me happy to see people take this project seriously. I think what would make this even better are a couple of unit tests and an acceptance test to prove everything continues to work with future changes.

I'm happy to help you with that aspect if you feel you need it.

**Comment by ahdekkers** [comment]
Hey! No worries, it's a neat repo :) Only just saw this but will get to writing those acceptance tests

**Comment by ahdekkers** [comment]
Let me know what you think @dnnrly. Added a dependency on [freeport](https://github.com/phayes/freeport) in order to setup the grpc server with any free port.

**Comment by dnnrly** [comment]
I have absolutely no problem with that dependency! Will hopefully get a bit of time to look at this in next couple of days.

**Comment by dnnrly** [comment]
Sorry for taking so long to around to this. The code looks good. Any chance that you'd be able to extend the documentation to include the new `grpc` option?

**Comment by ahdekkers** [comment]
Sure, will get to it in the near future

**Comment by ahdekkers** [comment]
Made the documentation, let me know what you think @dnnrly

**Review by dnnrly — APPROVED** [review]

**Comment by dnnrly** [comment]
Excellent! Thank you so much for your contribution. If you do twitter and you're prepared to share your handle, you just earned another follower. :smile:

**Pull request merged**
